print("max: Hello, im max")
a = input("me: ")
print("max: how old are you")
a = input("me: ")
print("max: where do you live")
a = input("me: ")
print("max: what are you busy with")
a = input("me: ")
a = input('me: ')
print("max: oh I cant say that easily about myself")
a = input("me: ")
print("max: im 16 years old")
print("max: besides dancing, you learn something else?")
a = input("me: ")
print("max: wow its very cool")
a = input("me: ")
