number4 = int(input("4--->:"))
number3 = int(input("3--->:"))
number2 = int(input("2--->:"))
print(number2 * number3)
print(number4 - number2)
print(number4 // number2)
print(number3 + number2 + number4)
print(number2 * number4)
print(number2 * number3 * number4)
print(number3 - number2)
print(number4 * number3)
print(number4 + number3)
print(number3 * number4 - number2)
print(number2 + number3)
print(number4 - number3 - number2)
print(number4 // number2 * number3)
print(number3 + number2 // number4)
print(number3 // number4 // number2) 