import turtle

#  we went to peint a palece

# step1: draw a square
turtle.color("light gray")
turtle.begin_fill()
turtle.speed(20)
turtle.forward(300)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(75)
turtle.left(90)
turtle.forward(200)
turtle.end_fill()
# end of square

# drawing a door
turtle.forward(1)
turtle.color("brown")
turtle.begin_fill()
turtle.right(90)
turtle.forward(50) #haight of the door
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.end_fill()



turtle.color("light gray")
turtle.begin_fill()
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(75)
turtle.left(90)
turtle.forward(200)
turtle.end_fill()

turtle.penup()
turtle.goto(75,199)
turtle.pendown()


turtle.color("black")
turtle.begin_fill()
turtle.right(155)
turtle.forward(80)
turtle.left(125)
turtle.forward(85)
turtle.end_fill()
#  end of  first roof


# paint the second roof
turtle.penup()
turtle.goto(225,199)
turtle.pendown()


turtle.color("black")
turtle.begin_fill()
turtle.left(183)
turtle.forward(80)
turtle.right(124)
turtle.forward(80)
turtle.end_fill()
# end of second roof


#drawing  first window
turtle.penup()
turtle.goto(20,110)
turtle.pendown()

turtle.color("white")
turtle.begin_fill()
turtle.left(151)
turtle.forward(45)
turtle.left(270)
turtle.forward(35)
turtle.left(270)
turtle.forward(45)
turtle.left(270)
turtle.forward(35)
turtle.end_fill()
#end first window

#draw the wall
turtle.penup()
turtle.goto(75,170)
turtle.pendown()


turtle.left(180)
turtle.forward(150)
turtle.left(90)
turtle.color("gray")
turtle.begin_fill()
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.left(270)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.left(270)
turtle.forward(10)
turtle.left(270)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.left(270)
turtle.forward(10)
turtle.left(270)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.left(270)
turtle.forward(10)
turtle.left(270)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.left(270)
turtle.forward(10)
turtle.left(270)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.left(270)
turtle.forward(10)
turtle.left(270)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.left(270)
turtle.forward(10)
turtle.left(270)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.end_fill()

#drawing  second window

turtle.penup()
turtle.goto(245,110)
turtle.pendown()
turtle.color("white")
turtle.begin_fill()
turtle.left(270)
turtle.forward(45)
turtle.left(270)
turtle.forward(35)
turtle.left(270)
turtle.forward(45)
turtle.left(270)
turtle.forward(35)
turtle.end_fill()
#end second window


#draw the third tower
turtle.penup()
turtle.goto(120,180)
turtle.pendown()
turtle.color("light gray")
turtle.begin_fill()
turtle.left(270)
turtle.forward(50)
turtle.right(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()


turtle.penup()
turtle.goto(180,230)
turtle.pendown()


turtle.color("black")
turtle.begin_fill()
turtle.left(210)
turtle.forward(60)
turtle.left(120)
turtle.forward(60)
turtle.end_fill()

#draw the third window

turtle.penup()
turtle.goto(137,195)
turtle.pendown()

turtle.color("white")
turtle.begin_fill()
turtle.left(120)
turtle.forward(25)
turtle.left(90)
turtle.forward(25)
turtle.left(90)
turtle.forward(25)
turtle.left(90)
turtle.forward(25)
turtle.end_fill()

#draw second square

turtle.penup()
turtle.goto(225,170)
turtle.pendown()

turtle.color("gray")
turtle.begin_fill()
turtle.forward(170)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(170)
turtle.right(90)
turtle.forward(150)
turtle.end_fill()

# draw the way
turtle.penup()
turtle.goto(125,0)
turtle.pendown()

turtle.color("gray")
turtle.begin_fill()
turtle.left(250)
turtle.forward(100)
turtle.right(20)
turtle.forward(150)
turtle.right(20)
turtle.forward(150)
turtle.right(20)
turtle.forward(500)


turtle.penup()
turtle.goto(175,0)
turtle.pendown()

turtle.left(80)
turtle.forward(80)
turtle.left(20)
turtle.forward(70)
turtle.left(20)
turtle.forward(170)
turtle.left(20)
turtle.forward(170)

#draw second wall

turtle.penup()
turtle.goto(0,120)
turtle.pendown()

turtle.color("gray")
turtle.begin_fill()
turtle.right(150)
turtle.forward(260)
turtle.left(90)
turtle.forward(120)
turtle.left(90)
turtle.forward(260)
turtle.end_fill()


#draw the flag
turtle.penup
turtle.goto(0,330)
turtle.pendown

turtle.color("black")
turtle.begin_fill()
turtle.left(180)
turtle.forward(180)
turtle.left(90)
turtle.forward(80)
turtle.left(90)
turtle.forward(180)
turtle.end_fill()


# draw in the flag  G 
turtle.penup()
turtle.goto(-130,320)
turtle.pendown()

turtle.color("white")
turtle.begin_fill()
turtle.left(180)
turtle.forward(40)
turtle.left(90)
turtle.forward(55)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(25)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(15)
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(35)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(15)
turtle.end_fill()

# draw in the flag  O
turtle.penup()
turtle.goto(-70,320)
turtle.pendown()

turtle.color("green")
turtle.begin_fill()
turtle.left(90)
turtle.forward(45)
turtle.left(90)
turtle.forward(55)
turtle.left(90)
turtle.forward(45)
turtle.left(90)
turtle.forward(55)
turtle.left(145)
turtle.forward(15)
turtle.left(35)
turtle.forward(33)
turtle.right(90)
turtle.forward(27)
turtle.right(90)
turtle.forward(33)
turtle.right(90)
turtle.forward(27)
turtle.end_fill()

# draw in the flag  A
turtle.penup()
turtle.goto(-15,265)
turtle.pendown()

turtle.color("white")
turtle.begin_fill()
turtle.left(105)
turtle.forward(58)
turtle.left(75)
turtle.forward(15)
turtle.left(72)
turtle.forward(58)
turtle.left(110)
turtle.forward(15)
turtle.left(60)
turtle.forward(17)
turtle.right(64)
turtle.forward(3)
turtle.right(55)
turtle.forward(17)
turtle.left(60)
turtle.forward(15)
turtle.end_fill()

#draw third wall

turtle.penup()
turtle.goto(300,120)
turtle.pendown()

turtle.color("gray")
turtle.begin_fill()
turtle.right(3)
turtle.forward(250)
turtle.right(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(250)
turtle.right(90)
turtle.forward(120)
turtle.end_fill()



# draw kings shuze
turtle.penup()
turtle.goto(-100,-210)
turtle.pendown()
turtle.color("black")
turtle.begin_fill()
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.end_fill()

turtle.penup()
turtle.goto(-120,-210)
turtle.pendown()
turtle.color("black")
turtle.begin_fill()
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.end_fill()

# draw the kings pants
turtle.penup()
turtle.goto(-135,-210)
turtle.pendown()
turtle.color("blue")
turtle.left(272)
turtle.begin_fill()
turtle.right(2)
turtle.forward(17)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(5)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(17)
turtle.left(90)
turtle.forward(45)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(45)
turtle.end_fill()

#draw the kings one hands
turtle.penup()
turtle.goto(-136 ,-165)
turtle.pendown()
turtle.color("black")
turtle.begin_fill()
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)

# draw the kings two hands

turtle.penup()
turtle.goto(-95 ,-165)
turtle.pendown()
turtle.color("black")
turtle.begin_fill()
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)

# draw the kings clothers
turtle.penup()
turtle.goto(-85,-165)
turtle.pendown()
turtle.color("red")
turtle.begin_fill()
turtle.forward(30)
turtle.left(90)
turtle.forward(62)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(62)
turtle.end_fill()

turtle.penup()
turtle.goto(-93,-165)
turtle.pendown()
turtle.color("black")
turtle.begin_fill()
turtle.left(90)
turtle.forward(20)

turtle.penup()
turtle.goto(-138,-165)
turtle.pendown()
turtle.color("black")
turtle.begin_fill()
turtle.forward(20)


# draw the kings had
turtle.penup()
turtle.goto(-127,-134)
turtle.pendown()
turtle.color("black")
turtle.forward(20)
turtle.right(90)
turtle.forward(25)
turtle.right(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(25)

# draw the mouth
turtle.penup()
turtle.goto(-110,-130)
turtle.pendown()
turtle.color("pink")
turtle.forward(10)
turtle.right(90)
turtle.forward(3)
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(3)
turtle.begin_fill()

#draw the kings eyes
turtle.penup()
turtle.goto(-110,-120)
turtle.pendown()
turtle.color("black")
turtle.forward(3)
turtle.left(90)
turtle.forward(3)
turtle.left(90)
turtle.forward(3)
turtle.left(90)
turtle.forward(3)

turtle.penup()
turtle.goto(-123,-120)
turtle.pendown()
turtle.color("black")

turtle.left(90)
turtle.forward(3)
turtle.left(90)
turtle.forward(3)
turtle.left(90)
turtle.forward(3)
turtle.left(90)
turtle.forward(3)

# draw the kings crown
turtle.penup()
turtle.goto(-95,-113)
turtle.pendown()
turtle.color("yellow")
turtle.forward(40)
turtle.right(90)
turtle.forward(15)
turtle.right(125)
turtle.forward(15)
turtle.left(90)
turtle.forward(20)
turtle.right(120)
turtle.forward(20)
turtle.right(250)
turtle.forward(15)
turtle.right(140)
turtle.forward(20)
turtle.end_fill()

# draw the queen

turtle.penup()
turtle.goto(-220,-220)
turtle.pendown()
turtle.color("black")
turtle.begin_fill()
turtle.right(88)
turtle.forward(10)
turtle.right(88)
turtle.forward(10)
turtle.right(88)
turtle.forward(10)
turtle.right(88)
turtle.forward(10)
turtle.end_fill()

turtle.penup()
turtle.goto(-200,-220)
turtle.pendown()
turtle.color("black")
turtle.begin_fill()
turtle.right(273)
turtle.forward(10)
turtle.right(270)
turtle.forward(10)
turtle.right(270)
turtle.forward(10)
turtle.right(270)
turtle.forward(10)
turtle.end_fill()

# draw a dress

turtle.penup()
turtle.goto(-170,-210)
turtle.pendown()
turtle.color("pink")
turtle.begin_fill()
turtle.right(90)
turtle.forward(85)
turtle.right(120)
turtle.forward(70)
turtle.right(60)
turtle.forward(30)
turtle.right(70)
turtle.forward(70)
turtle.end_fill()

# draw the queen had

turtle.penup()
turtle.goto(-190,-150)
turtle.pendown()
turtle.color("black")
turtle.begin_fill()
turtle.right(200)
turtle.forward(25)
turtle.right(270)
turtle.forward(30)
turtle.right(270)
turtle.forward(25)


#draw the queen eyes

turtle.penup()
turtle.goto(-195,-138)
turtle.pendown()
turtle.color("black")
turtle.begin_fill()
turtle.right(90)
turtle.forward(3)
turtle.right(90)
turtle.forward(3)
turtle.right(90)
turtle.forward(3)
turtle.right(90)
turtle.forward(3)


turtle.penup()
turtle.goto(-212,-138)
turtle.pendown()
turtle.color("black")
turtle.begin_fill()
turtle.right(90)
turtle.forward(3)
turtle.right(90)
turtle.forward(3)
turtle.right(90)
turtle.forward(3)
turtle.right(90)
turtle.forward(3)

#draw the queens mouth
turtle.penup()
turtle.goto(-209,-140)
turtle.pendown()
turtle.color("red")
turtle.begin_fill()
turtle.forward(2)
turtle.left(90)
turtle.forward(8)
turtle.left(90)
turtle.forward(2)
turtle.left(90)
turtle.forward(8)
turtle.end_fill()


# draw thr queens crown
turtle.penup()
turtle.goto(-190,-126)
turtle.pendown()
turtle.color("yellow")
turtle.begin_fill()
turtle.forward(30)
turtle.right(90)
turtle.forward(15)
turtle.right(145)
turtle.forward(10)
turtle.left(100)
turtle.forward(15)
turtle.right(100)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.right(130)
turtle.forward(13)
turtle.end_fill()

#draw the queen hends
turtle.penup()
turtle.goto(-190,-150)
turtle.pendown()
turtle.color("red")
turtle.begin_fill()
turtle.left(95)
turtle.forward(15)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(5)
turtle.right(70)
turtle.forward(33)
turtle.left(70)
turtle.forward(47)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(5)
turtle.left(71)
turtle.forward(32)
turtle.end_fill()

# draw contour
turtle.width(2)
turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.color("black")
turtle.begin_fill()
turtle.left(109)
turtle.forward(260)
turtle.right(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(260)

turtle.goto(0,0)
turtle.pendown()
turtle.color("black")
turtle.goto(0,0)
turtle.pendown()
turtle.color("black")
turtle.begin_fill()
turtle.right(0)
turtle.forward(550)
turtle.right(270)
turtle.forward(120)


turtle.right(270)
turtle.forward(250)
turtle.right(270)
turtle.forward(120)
turtle.right(90)
turtle.forward(75)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(75)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(225)
turtle.right(90)
turtle.forward(200)
turtle.right(270)
turtle.forward(75)
turtle.right(270)
turtle.forward(200)
turtle.right(270)
turtle.forward(125)
turtle.right(270)

turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(270)
turtle.forward(50)
turtle.right(270)
turtle.forward(180)
turtle.right(270)
turtle.forward(10)
turtle.right(270)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(270)
turtle.forward(10)
turtle.right(270)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(270)
turtle.forward(10)
turtle.right(270)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(270)
turtle.forward(10)
turtle.right(270)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(270)
turtle.forward(10)
turtle.right(270)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(270)
turtle.forward(10)
turtle.right(270)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(270)
turtle.forward(10)
turtle.right(270)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(270)
turtle.forward(10)
turtle.right(270)
turtle.forward(180)
turtle.right(270)
turtle.forward(150)
turtle.right(270)
turtle.forward(180)
turtle.right(270)
turtle.forward(10)
turtle.right(270)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(270)
turtle.forward(10)
turtle.right(270)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.right(270)
turtle.forward(5)
turtle.right(90)
turtle.forward(50)
turtle.right(270)
turtle.forward(60)
turtle.right(270)
turtle.forward(50)

turtle.penup()
turtle.goto(244,155)
turtle.pendown()

turtle.color("black")
turtle.begin_fill()
turtle.forward(48)
turtle.right(270)
turtle.forward(38)
turtle.right(270)
turtle.forward(48)
turtle.right(268)
turtle.forward(40)

turtle.penup()
turtle.goto(20,155)
turtle.pendown()

turtle.right(180)
turtle.forward(35)
turtle.right(91)
turtle.forward(48)
turtle.right(90)
turtle.forward(35)
turtle.right(90)
turtle.forward(48)


turtle.penup()
turtle.goto(-44,295)
turtle.pendown()

turtle.color("black")
turtle.begin_fill()
turtle.right(30)
turtle.forward(15)
turtle.right(130)
turtle.forward(15)
turtle.right(110)
turtle.forward(13)
turtle.end_fill()


# draw a lake

turtle.penup()
turtle.goto(500,350)
turtle.pendown()

turtle.begin_fill()
turtle.color("yellow")
turtle.circle(30)
turtle.end_fill()

#draw the conture 

turtle.penup()
turtle.goto(200,150)
turtle.pendown()

turtle.color("black")
turtle.begin_fill()
turtle.forward(25)

turtle.penup()
turtle.goto(240,180)
turtle.pendown()
turtle.right(180)
turtle.forward(25)

turtle.penup()
turtle.goto(130,120)
turtle.pendown()
turtle.right(180)
turtle.forward(25)

turtle.penup()
turtle.goto(170,100)
turtle.pendown()
turtle.right(180)
turtle.forward(25)

turtle.penup()
turtle.goto(100,80)
turtle.pendown()
turtle.right(180)
turtle.forward(25)

turtle.penup()
turtle.goto(30,180)
turtle.pendown()
turtle.forward(25)

turtle.penup()
turtle.goto(180,100)
turtle.pendown()
turtle.forward(25)

turtle.penup()
turtle.goto(30,55)
turtle.pendown()
turtle.forward(25)

turtle.penup()
turtle.goto(50,90)
turtle.pendown()
turtle.right(180)
turtle.forward(25)

turtle.penup()
turtle.goto(-50,100)
turtle.pendown()
turtle.right(180)
turtle.forward(25)

turtle.penup()
turtle.goto(-20,20)
turtle.pendown()
turtle.right(180)
turtle.forward(21)

turtle.penup()
turtle.goto(-90,60)
turtle.pendown()
turtle.right(180)
turtle.forward(30)

turtle.penup()
turtle.goto(-160,100)
turtle.pendown()
turtle.forward(40)

turtle.penup()
turtle.goto(-230,50)
turtle.pendown()
turtle.forward(31)

turtle.penup()
turtle.goto(250,80)
turtle.pendown()
turtle.right(180)
turtle.forward(35)

turtle.penup()
turtle.goto(230,40)
turtle.pendown()
turtle.forward(20)

turtle.penup()
turtle.goto(350,70)
turtle.pendown()
turtle.forward(30)

turtle.penup()
turtle.goto(430,100)
turtle.pendown()
turtle.forward(25)

turtle.penup()
turtle.goto(490,45)
turtle.pendown()
turtle.forward(35)

turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.right(181)
turtle.forward(700)

turtle.penup()
turtle.goto(500,0)
turtle.pendown()
turtle.left(180)
turtle.forward(200)

#draw a tree

turtle.penup()
turtle.goto(-320,150)
turtle.pendown()

turtle.color("brown")
turtle.begin_fill()
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

turtle.penup()
turtle.goto(-345,150)
turtle.pendown()

turtle.color("green")
turtle.begin_fill()
turtle.circle(80)
turtle.end_fill()








turtle.exitonclick()